version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - DATABASE_NAME=mydatabase
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - backend

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
